### ISSUE TITLE
Update FFmpeg version

### ISSUE THREAD

**Issue by tstevens** [homebridge/ffmpeg-for-homebridge#16]
**Is your feature request related to a problem? Please describe:**
I am trying to utilize the V4L2 codecs (specifically h264_v4l2m2m) and the current ffmpeg version is missing some patches which cause the video to encode with a green tint. I have been able to manually build a ffmpeg version locally on the 4.3.1 release which solves the problem.

**Describe the solution you'd like:**

Provide an updated build using a release 4.3.x or greater version of ffmpeg.

**Describe alternatives you've considered:**

I have attempted to modify this project to do so but I am unable to figure out the build process (qemu + the GitHub builder specifically) and I have also had compile failures trying to hack up the docker file to build locally.

**Additional context:**

My ultimate goal is to enable hardware decoding/encoding within docker containers. I'm utilizing docker-homebridge  + homebridge-camera-ffmpeg on a Raspberry Pi and while I have been able to get the codecs working inside the container the encoder output is currently green which makes it quite a bit less exciting to share with others who would likely appreciate this capability.

**Comment by oznu** [comment]
Hi @tstevens,

I'd be happy to accept a PR that includes these changes. Keep in mind that the compiled binaries must work on a variety of systems and not require any special system configuration.

**Comment by tstevens** [comment]
I was attempting to do so, but I wasn't able to figure out how to build it locally. Is there a script or process for building these that I am missing? I see qemu being added to the container builds but I can't see where it is invoked or used. I have hacked up a build-ffmpeg locally and tried to build/run the resulting container to create a build, the container starts and runs but that build fails for a compilation error before even reaching my changed ffmpeg version in the build-ffmpeg script.

As for special configuration, the v4l2m2m codecs are already built into the existing ffmpeg builds provided here so I wouldn't be changing the ffmpeg configuration or require anything special with the system to do this.

**Comment by oznu** [comment]
Thanks, i misunderstood that all you wanted was ffmpeg v4.3.1 😄 

v0.0.9 includes ffmpeg v4.3.1.

**Comment by tstevens** [comment]
Thanks! 4.3.1 was all I was looking for.
